### ISSUE TITLE
Missing VFPExMAPI.fll dependency in repository.

### ISSUE THREAD

**Issue by rschummer** [DougHennig/ErrorHandler#2]
## 📝 Provide detailed reproduction steps (if any)

Add source code to project
Build project

### ✔️ Expected result

no errors from the build

### ❌ Actual result

Program j:\wlcproject\whitelight\foxcommand\sferrorhandler\sfmail.prg has the following errors:
    Unknown EMCREATEMESSAGEEX - Undefined
    Unknown EMCREATEMESSAGE - Undefined
    Unknown EMADDRECIPIENT - Undefined
    Unknown EMADDATTACHMENT - Undefined
    Unknown EMSEND - Undefined

Dependency for VFPExMAPI.fll, which is not included in the repository. I grabbed it from the SFMail project, where it is included.

**Comment by DougHennig** [comment]
Fixed in the latest build: I added VFPExMAPI.fll to the repository but also changed SFMail to call its methods indirectly so no Project Manager error if the FLL can't be found.
