### ISSUE TITLE
Getting "oError is not an object" message

### ISSUE THREAD

**Issue by Terterola** [DougHennig/ErrorHandler#3]
## 📝 Provide detailed reproduction steps (if any)

I'm running the following lines in my MAIN.PRG project file:

Public oError
oError = NewObject([SFErrorMgr],[errorhandler\sferrormgr.vcx],[],[Boreo],.t.,'oError')

### ✔️ Expected result

I was expecting to startup the error handler... I did declare oError variable as public, but for some reason, the object is not created. 

### ❌ Actual result

FoxPro throws a message "oError is not an object". 

Any clue?
TIA.

## 📷 Screenshots

<img width="672" alt="Captura de Tela 2022-12-27 às 16 03 49" src="https://user-images.githubusercontent.com/6319010/209711792-2971a244-2aff-4ec0-981c-0a236ec727d7.png">

**Comment by Terterola** [comment]
For your knowledge, I created a subfolder in my project where I put all the ErrorHandler classes and dependencies in it.

**Comment by DougHennig** [comment]
I suggest tracing the code in the Init method of SFErrorMgr to see where it fails.

**Comment by Terterola** [comment]
Ok, Doug! Tracing is our best friend, indeed. There was a lot of files to keep track adding to the project and I forgot adding the .h files. Everything is working now.  Thank you!
